### ISSUE TITLE
dropbox stays on screen when clicking back

### ISSUE THREAD

**Issue by yehudahkay** [koss-shtukert/laravel-nova-select2-auto-complete#36]
Hi and thank you for the package!

I am in chrome on windows 10, if I open the dropdown and then click the back button the dropdown remains on the screen. 

![image](https://user-images.githubusercontent.com/9964988/65677751-d4993680-e05a-11e9-9525-ec2c5d4e81ad.png)

**Comment by koss-shtukert** [comment]
Hi @yehudahkay 
Could you provide more details?
Do you open select box in the index page?

**Comment by yehudahkay** [comment]
I am going into the detail page, opening the dropdown, clicking back and then i have the screenshot above

**Comment by koss-shtukert** [comment]
@yehudahkay but how you can edit any fields in the detail page?
Maybe you open edit/create a page? But in this case, I don't have any bugs with open select box and go back

**Comment by yehudahkay** [comment]
Yes the issue is after opening the edit page

**Comment by koss-shtukert** [comment]
Hi @yehudahkay, I reproduce a bug.
Unfortunately, this is a global bug on Nova, because the same bug is with a date component...

![image](https://user-images.githubusercontent.com/709096/66634374-9a609500-ec15-11e9-9754-dff0722b4bdb.png)

But I fixed this issue on my component :)
Please see [Release v1.20](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.20)

**Comment by yehudahkay** [comment]
I thought it might be a general bug with nova, you're awesome. I'm on vacation now but I'll check when I get back, thank you!!!

**Comment by koss-shtukert** [comment]
Also, I open an issue in the Nova issues page:
https://github.com/laravel/nova-issues/issues/2033

Have a nice vacation ;)
